server:
  port: ${service.registry.port}

spring:
  application:
    name: ${service.registry.name}

eureka:
  instance:
    hostname: ${service.registry.host}
    metadata-map:
      hostname: ${eureka.instance.hostname}
      securePort: ${server.port}
    secureVirtualHostName: ${spring.application.name}
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

  server:
    enable-self-preservation: false

endpoints:
  default:
    web:
      enabled: true

info:
  app:
    version: "@project.version@"
    artifact: "@project.artifactId@"
    group: "@project.groupId@"
  java:
    version: "@java.version@"
